import Head from 'next/head'
import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'
import { useState } from 'react';
export default function Home({ quote }) {
  function getQuote(obj) {
    var size = Object.keys(obj).length;
    return obj[Math.floor(Math.random() * (size - 1))].quote
  }
  const [quoteForSession, setquoteForSession] = useState(getQuote(quote));
  return (
    <div>
      <Head>
        <title>Albert Einstein Quotes API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="container mx-auto text-center p-2">
          <div className="heading-container">
            <h1 className='text-3xl font-bold my-2 mt-12'>Albert Einstein Quotes API</h1>
            <h3 className='text-md my-2 text-gray-600'>A free REST API for random Albert Einstein Quotes.</h3>
            <p className='my-4 text-blue-500 hover:text-blue-600 hover:underline'>
              <Link href='https://einstein.ishn.xyz/api'>
                <a target={'_blank'}>
                  <p className="cursor-ne-resize">https://einstein.ishn.xyz/api</p>
                </a>
              </Link>
            </p>
          </div>
          <div className="quote-container bg-gray-200/50 p-8 my-12 rounded-md lg:mx-32 md:mx-20 mx-4">
            <p>
              &#8220;{quoteForSession}&#8220;
            </p>
          </div>
          <div className="quotes-interaction-container my-12 space-x-2.5" >
            <a onClick={() => setquoteForSession(getQuote(quote))}>
              <button
                className="bg-transparent hover:bg-blue-400 text-blue-500 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                Refresh
              </button>
            </a>
            <Link href={`https://twitter.com/intent/tweet?text=${quoteForSession} -Albert Einstein (via einstein.ishn.xyz)`}>
              <a target={'_blank'}>
                <button
                  className="bg-transparent hover:bg-blue-400 text-blue-500 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                  Tweet
                </button>
              </a>
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
export async function getStaticProps() {
  const supabaseAdmin = createClient(
    process.env.NEXT_SUPABASE_URL,
    process.env.NEXT_SUPABASE_KEY,
  )
  const { data } = await supabaseAdmin
    .from("quotes-api-table")
    .select("*")
  return {
    props: {
      quote: data
    }
  }
}